apiVersion: v1
kind: Service
metadata:
  name: dice-game-service
spec:
  selector:
    app: dice-game
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001  

